services:
  strategy-prod-v8-es:
    build: .
    image: strategy-prod-v8-es:local
    container_name: strategy-prod-v8-es
    restart: unless-stopped
    environment:
      DATABENTO_API_KEY: "${DATABENTO_API_KEY}"
    volumes:
      - ./logs:/app/logs
    ports:
      - "127.0.0.1:5555:5555"
      - "127.0.0.1:5556:5556"
